# Generated by Django 4.0.5 on 2023-02-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estiem', '0003_alter_category_options_alter_estiem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estiem',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Событие в Эстиме', 'verbose_name_plural': 'События в Эстиме'},
        ),
        migrations.AlterField(
            model_name='estiem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
