# Generated by Django 4.0.5 on 2023-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estiem', '0004_alter_estiem_options_alter_estiem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='estiem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
