# Generated by Django 4.0.5 on 2023-03-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estiem', '0006_alter_category_slug_alter_estiem_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Вид')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид события',
                'verbose_name_plural': 'Виды событий',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='estiem',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estiem.kind', verbose_name='Виды событий'),
        ),
    ]
